### ISSUE TITLE
Using stop button breaks vim key input

### ISSUE THREAD

**Issue by ldelossa** [rcarriga/nvim-dap-ui#188] opened 2022-12-06 03:50 UTC
Hello,

When using nvim-dap-ui and using the "stop" debugging button on the repl, when nvim-ui-dap closes (via hooks suggested in th readme/texts) I can no longer use vim correctly.

What happen is, is a bit hard to explain, but it seems like there is possible an autocommand sticking around that takes you out of insert mode and places you back to normal mode. Does this sound possible?

This does not happen if I call "DapClose" directly.

**Comment by rcarriga** [comment] 2022-12-10 16:36
It does sound like an autocommand issue. You can try setting the `verbose` setting to at least `9`. I'd also recommend setting `verbosefile`

**Comment by ldelossa** [comment] 2022-12-11 01:38
Which settings are these?

**Comment by rcarriga** [comment] 2022-12-11 16:29
See `:help verbose` and `:help verbosefile`

**Comment by ldelossa** [comment] 2022-12-11 16:46
Gotchya, thought you meant in dap-ui

**Comment by stickperson** [comment] 2022-12-16 06:43
@ldelossa are you using `console` to `integratedTerminal` in your config by any chance? I noticed I'm seeing this same behavior but only when I'm using `nvim-dap-python` which [sets that](https://github.com/mfussenegger/nvim-dap-python/blob/27a0eff2bd3114269bb010d895b179e667e712bd/lua/dap-python.lua#L79) by default. If I comment out that part the bug goes away.

**Comment by ldelossa** [comment] 2022-12-16 12:00
Dont think so. Im using lldb.

**Comment by tristone13th** [comment] 2023-04-14 01:16
I'm facing the same issue, every keystroke will return the neovim to normal mode after I close the dapui/dap.

**Comment by rcarriga** [comment] 2023-04-15 13:30
There's an issue with nvim-dap and neovim which sounds similar to this. Apparently nightly fixes the problem but I can't reproduce to test. See #262

**Comment by tristone13th** [comment] 2023-04-15 13:39
> There's an issue with nvim-dap and neovim which sounds similar to this. Apparently nightly fixes the problem but I can't reproduce to test. See #262

Thanks, I have checked, and both nightly and v8.3.0 neovim works fine, v9.0.0 is broken.

**Comment by st0nie** [comment] 2023-04-17 04:41
> > There's an issue with nvim-dap and neovim which sounds similar to this. Apparently nightly fixes the problem but I can't reproduce to test. See #262
> 
> Thanks, I have checked, and both nightly and v8.3.0 neovim works fine, v9.0.0 is broken.

Yeah, but nightly seems to break neodev.nvim.
I use v8.3.0 and it works fine.

**Comment by rcarriga** [comment] 2023-05-29 20:56
Closing as this is fixed by neovim, not nvim-dap-ui

**Closed by rcarriga** 2023-05-29 20:56 UTC
