### ISSUE TITLE
Cannot evaluate code from visual selection

### ISSUE THREAD

**Issue by przepompownia** [rcarriga/nvim-dap-ui#80] opened 2022-02-11 01:34 UTC
https://github.com/przepompownia/dap-ui-test

The above example repo has been created to illustrate #78 but I still cannot reproduce that error on this environment. 

As a side effect I caught another error: I cannot evaluate "complex" expression (`$x + 1` on the example). 

Please look at README and compare evaluation using dap-ui (done from the script at the start) and dap (manual with `,dh`). 

Actual:
![image](https://user-images.githubusercontent.com/11404453/153524659-f66a0b06-c2fd-4f05-a2db-54236b219abc.png)
With nvim-dap:
![image](https://user-images.githubusercontent.com/11404453/153524700-6a2fd4aa-3371-4c93-9f41-2cf955d30312.png)

**Comment by rcarriga** [comment] 2022-02-12 09:15
Thanks for the excellent reproduction, very helpful! :grin: Unfortunately it looks like this is expected behaviour and nvim-dap is actually not sending the correct request arguments. For an [evaluate request](https://microsoft.github.io/debug-adapter-protocol/specification#Requests_Evaluate) there is a `context` argument, which is set to `hover` for `dapui.hover` and to `watch` for the watches window. nvim-dap is just hardcoding this context to `repl` which appears to make the PHP debugger act differently. 

I do not wish to change the requests being sent by nvim-dap-ui as they are following the spec. Best solution IMO would be to open an issue on PHP's debugger and ask why this behaviour exists

**Comment by przepompownia** [comment] 2022-02-12 13:54
Looking at the communication _dapui_ - _dap_ - _vscode-php-debug_ - _xdebug_ in details can take some my free time, so let keep the issue open. Without this effort I can observe what XDebug logs in `/tmp/xdebug.log`.

After dapui evaluation:
```
[155268] [Step Debug] <- property_get -i 18 -d 0 -c 0 -n "$x + 1"
[155268] [Step Debug] -> <response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="https://xdebug.org/dbgp/xdebug" command="property_get" transaction_id="18" status="break" reason="ok"><error code="300"><message><![CDATA[can not get property]]></message></error></response>
```
After dap evaualtion (hover):
```
[155268] [Step Debug] <- eval -i 33 -- JHggKyAx
[155268] [Step Debug] -> <response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="https://xdebug.org/dbgp/xdebug" command="eval" transaction_id="33"><property type="int"><![CDATA[2]]></property></response>
```
but (offtopic for this issue) not only it - it also sends a similar request but probably does not use its response:
```
[155268] [Step Debug] <- property_get -i 39 -d 0 -c 0 -n "$x + 1"                                                      
[155268] [Step Debug] -> <response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="https://xdebug.org/dbgp/xdebug" command="property_get" transaction_id="39" status="break" reason="ok"><error code="300"><message><![CDATA[can not get property]]></message></error></response> 
```

**Comment by przepompownia** [comment] 2022-02-12 17:00
Indeed, from `dap.log`'s perspective I see that the same expression is evaluated differently depending on `context`:
```
[ DEBUG ] 2022-02-12T17:46:46Z+0100 ] ...dap-ui-test/pack/bundle/opt/nvim-dap/lua/dap/session.lua:839 ] "request"     {  arguments = {    
    context = "hover",    
    expression = "$x + 1",
    frameId = 1  
  },
  command = "evaluate",
  seq = 14,
  type = "request"
}
[ DEBUG ] 2022-02-12T17:46:46Z+0100 ] ...dap-ui-test/pack/bundle/opt/nvim-dap/lua/dap/session.lua:560 ] {
  command = "evaluate",  message = "can not get property",
  request_seq = 14,
  seq = 18,
  success = false,  type = "response"
}
```

```
[ DEBUG ] 2022-02-12T17:54:01Z+0100 ] ...dap-ui-test/pack/bundle/opt/nvim-dap/lua/dap/session.lua:839 ]        "request"       {                                                                                        
  arguments = {                                                                                                                                                                                                                                 
    context = "repl",                                                                                                                                                                                                                           
    expression = "$x + 1",                                                                                                                                                                                                                      
    frameId = 1                                                                                                                                                                                                                                 
  },                                                                                                                                                                                                                                            
  command = "evaluate",                                                                                                                                                                                                                         
  seq = 15,                                                                                                                                                                                                                                     
  type = "request"                                                                                                                                                                                                                              
}                                                                                                                                                                                                                                               
[ DEBUG ] 2022-02-12T17:54:01Z+0100 ] ...dap-ui-test/pack/bundle/opt/nvim-dap/lua/dap/session.lua:560 ] {                                                                                                                                       
  body = {                                                                                                                                                                                                                                      
    result = "2",                                                                                                                                                                                                                               
    variablesReference = 0                                                                                                                                                                                                                      
  },                                                                                                                                                                                                                                            
  command = "evaluate",                                                                                                                                                                                                                         
  request_seq = 15,                                                                                                                                                                                                                             
  seq = 19,                                                                                                                                                                                                                                     
  success = true,                                                                                                                                                                                                                               
  type = "response"                                                                                                                                                                                                                             
}
```

**Comment by przepompownia** [comment] 2022-02-13 16:37
@rcarriga how `evaluate` with `hover` as the context is implemented for adapters known for you? Is it possible to evaluate expressions able to change anything (`++$x`, `$x = 2`,  `exec('rm ...')` etc.)? Please look at the linked issue. 

On the UI side I would like to have both such "safe" and "unsafe" (possibly with the warning dialog) actions.

**Comment by rcarriga** [comment] 2022-02-14 07:45
I think I'd be happy providing an option for the `eval` function to have an `unsafe` version which would use the `repl` context.

```lua
dapui.eval("$x + 1") -- Uses "hover" context
dapui.eval("$x + 1", { unsafe = true }) -- Uses "repl" context

```

**Comment by przepompownia** [comment] 2022-02-14 11:16
> I think I'd be happy providing an option for the `eval` function to have an `unsafe` version which would use the `repl` context.
> 
> ```lua
> dapui.eval("$x + 1") -- Uses "hover" context
> dapui.eval("$x + 1", { unsafe = true }) -- Uses "repl" context
> ```

It looks backward compatible and simple. The only thing is naming, remembering that `evaluate` has four allowed context values.

**Comment by rcarriga** [comment] 2022-02-16 07:44
You're right, better to not abstract it since each adapter can implement differently. I've added a settings table to the `eval` function which accepts a `context` value

**Comment by przepompownia** [comment] 2022-02-16 10:34
On the test environment with `enter = true` Isee a visual selection moved to the float window - it would be good to switch to normal mode then. 
![image](https://user-images.githubusercontent.com/11404453/154244994-b66d0669-8fa0-4511-a6a4-520c3959642f.png)
(with `keymap.set({'x'}, ',de', function() dapui.eval(nil, {enter = true, context = 'repl'}) end, opts)`).

Great change! I'll test it on a real environment. :tada:

**Comment by przepompownia** [comment] 2022-02-16 20:23
@rcarriga please test newly created float window that contains lots of lines. In short, I get animated window and large amount of requests to adapter. In effect, the debugger log file get the size that exhaust the free space on a filesystem and nvim needs to kill with `-9`. I need some free time to prepare some reproduction.

**Comment by rcarriga** [comment] 2022-02-17 08:18
> On the test environment with enter = true I see a visual selection moved to the float window - it would be good to switch to normal mode then.

Added in latest commit :grin: 

Going to close this issue as the original problem has been resolved and there's a separate issue for the other problem

**Closed by rcarriga** 2022-02-17 08:18 UTC

**Comment by przepompownia** [comment] 2022-02-17 10:09
Confirmed switching to normal mode, thanks!
