### ISSUE TITLE
Evaluating expression runs out of memory

### ISSUE THREAD

**Issue by HiPhish** [rcarriga/nvim-dap-ui#66] opened 2021-11-14 16:28 UTC
I have a problem when I use the `dapui.eval` function: the first few times it works well, then Neovim becomes blocked for several second. With each subsequent call Neovim gets less and less responsive. Eventually I get the error message `Error executing vim.schedule lua callback: not enough memory`. I am trying to debug the following toy example:

```python
def add(x, y):
    if x == 0:
        return y
    return add(x - 1, y + 1)


class MyClass(object):

    def __init__(self):
        """TODO: to be defined. """


result = add(3, 4)
print(result)
```

My breakpoint is on line 2 and it is stopped during the first iteration. The debug adapter is [debugpy](https://github.com/microsoft/debugpy). Here is my relevant configuration for the evaluation mapping, although I don't see anything wrong with it:

```vim
function! s:dapui_eval()
	let s:expr = input('DAP expression: ')
	if empty(s:expr)
		return
	endif

	call luaeval('require("dapui").eval(_A)', s:expr)
endfunction

nnoremap <M-k> <Cmd>call <SID>dapui_eval()<CR>
```

I always enter `x` at the prompt to evaluate the variable `x`. Any idea? A memory leak perhaps? I have attached a screenshot; as you can see there is nothing else going on in the DAP UI. I have not experienced this issue with `dap.ui.widgets.hover`.

![Screenshot_20211114_172207](https://user-images.githubusercontent.com/4954650/141689476-002f563f-3533-4cfd-87a7-f60420cc2a79.png)

**Comment by againxx** [comment] 2021-11-19 02:31
I also encountered this problem with an error message `Error executing vim.schedule lua callback table overflow`

**Comment by rcarriga** [comment] 2021-11-22 18:23
It does look like a memory leak but I can't see any state being held onto that would cause this. I also can't replicate unfortunately. Can you provide more details:
- Versions of debugpy and neovim (also I'm assuming you're using latest of nvim-dap and nvim-dap-ui)
- A full nvim-dap log at DEBUG level (See `:help dap.set_log_level()`, please clear the existing file before recording)
- If the above doesn't help then I may require a minimal init.lua/init.vim

**Comment by HiPhish** [comment] 2021-11-25 22:02
I have updated the all plugins and the issue still persists. Here is the information you have requested.

>     * Versions of debugpy and neovim (also I'm assuming you're using latest of nvim-dap and nvim-dap-ui)

- Debugpy version 1.5.1
- Neovim 0.5.1, LuaJIT 2.1.0-beta3 (from the [Void](https://voidlinux.org/) repositories
- nvim-dap commit `4e8bb7ca12dc8ca6f7a500cbb4ecea185665c7f1`
- nvim-dap-ui commit `649e0fee4f0b8dc6305dd29065c7623c3dc6a032`

>     * A full nvim-dap log at DEBUG level (See `:help dap.set_log_level()`, please clear the existing file before recording)

[dap.log](https://github.com/rcarriga/nvim-dap-ui/files/7605358/dap.log)

**Comment by rcarriga** [comment] 2021-11-27 12:20
Can you please try with the latest commit?

**Comment by HiPhish** [comment] 2021-11-28 11:19
I tried the latest commit, but the issue still remains. After around 18 evaluations the editor start becoming noticeably sluggish. However, with a minimal configuration I cannot reproduce the issue. It might simply be that a minimal configuration requires less memory overall and that it would take several hundred evaluations to run out of memory.

Here is the minimal configuration; you will have to change the file extensions back to `vim` and `lua` (GitHub does not allow me to upload `.vim` and `.lua` files):

- [init.vim](https://github.com/rcarriga/nvim-dap-ui/files/7613397/init.txt)
- [plugin/dap.lua](https://github.com/rcarriga/nvim-dap-ui/files/7613399/dap.txt)

I apply this custom configuration to Neovim by setting the `XDG_CONFIG_HOME` and `XDG_DATA_HOME` environment variables:

```sh
XDG_DATA_HOME=~/Desktop/fake-xdg/share/ XDG_CONFIG_HOME=~/Desktop/fake-xdg/config/ nvim derp.py
```

Afterwards I press `<F8>` to get the debugger running and use `<M-k>` to open the prompt. Unfortunately I have not been able to automate evaluating an expression and then closing the floating window, so I have to do that step by hand over and over. Here is the log:

[dap.log](https://github.com/rcarriga/nvim-dap-ui/files/7613413/dap.log)

**Comment by rcarriga** [comment] 2021-11-28 13:56
OK if you can't reproduce with a minimal config, then it's possible that another plugin is interacting strangely with nvim-dap-ui. Since I can't test myself, I've created a branch `diagnose-oom` which you can use to open multiple eval windows quickly using this function
```lua
function run_eval()
  for i = 1, 100, 1 do
     require'dapui'.eval()
  end
end
```
so you should be able to reproduce quickly. If so then you could try bisecting your config (removing half of your plugins and trying to reproduce, and then continue bisecting whichever plugins it still happens with until you can find the one). I can't really do anything more until I can reproduce I'm afraid

**Comment by FelipeMarcelino** [comment] 2021-12-01 18:44
Same problem here. 

![image](https://user-images.githubusercontent.com/15383718/144294584-353feffe-9e13-4e30-9064-7242161a0c69.png)

Some kind of overflow after adding some variable expressions in expression windows.

**Comment by rcarriga** [comment] 2021-12-01 19:21
@FelipeMarcelino Can you provide more info so I can try reproduce? Debug adapter, sample file, steps taken, version of neovim etc. Right now I have no way of reproducing this so I can't help. Also do you have any other plugins that use nvim-dap?

**Comment by FelipeMarcelino** [comment] 2021-12-01 19:36
Neovim Version: 0.5.1

List of plugins that can interact with dap:
nvim-dap-python
nvim-dap-ui
nvim-dap 
telescope-dap.nvim 

Debug adapter:
debugpy 1.5.1

Sample  file? So they are really small, but the code has almost 4000 lines. 

Not sure about steps taken 

@rcarriga

**Comment by rcarriga** [comment] 2021-12-02 09:06
OK @againxx I checked your dotfiles and saw you're using nvim-dap-virtual-text. It was having memory issues which I've opened a PR for, so for anyone with this issue that is using nvim-dap-virtual-text that should help you. @HiPhish @FelipeMarcelino I'm still not sure why you're having issues as it doesn't seem like you're using that plugin. @FelipeMarcelino If you follow the steps from the original post do you get the same issue?

**Comment by againxx** [comment] 2021-12-02 09:20
@rcarriga Thank you very much! I will temporarily disable nvim-dap-virtual-text to see if this can fix my issue. I will come back if I have any discoveries.

**Comment by FelipeMarcelino** [comment] 2021-12-02 12:59
@rcarriga  I realized that I am using nvim-dap-virtual-text as well. So I will disable this feature by now.

**Comment by HiPhish** [comment] 2021-12-02 22:36
I feel so stupid now, I have nvim-dap-virtual-text as well. Now that I have removed that plugin I am no longer running out of memory. I am really sorry for wasting your time like this. The issue can be closed now as far as I am concerned.

**Comment by rcarriga** [comment] 2021-12-03 09:00
Ah glad to hear it's all fixed anyway! Very understandable why you thought it was dap-ui :sweat_smile: FYI nvim-dap-virtual-text has merged the fix so you can re-enable it now if you wish

**Closed by rcarriga** 2021-12-03 09:00 UTC
Labels: bug
