### ISSUE TITLE
Neovim filetype detection stopped working after d608b76

### ISSUE THREAD

**Issue by abigagli** [rcarriga/nvim-dap-ui#219] opened 2023-01-28 19:01 UTC
I left a comment in the (huge) commit, but I though opening an issue to give some more details:

after [d608b76](https://github.com/rcarriga/nvim-dap-ui/commit/d608b7628aeafa36cf5e3439def832e9789b7ff8) filetype detection doesn't work for me.
For any type I open, I get `filetype unkown` which cascades into missing syntax highlighting, missing lsp attach etc etc..
The only way to make it work is to manually specify the filetype for every file I open...
This commit is huge and I'm no nvim expert so I don't think I can't understand what's causing the problem, but rolling back to the parent commit solves the issue for me.

**Comment by nyngwang** [comment] 2023-01-29 03:12
> after d608b76 filetype detection doesn't work for me.

I did experience something similar: Some of my `FileType` autocmds on custom `filetype` didn't work as expected. Sometimes either `vim.bo.filetype` or `vim.bo.buftype` was just not set at the proper timing: It seems to be set since when you run `print(vim.bo.filetype)`(or `set ft?`) on the buffer you want to test with you will get the value. But your autocmds just cannot detect them. And my conclusion is: The problem seems to be related to the fact that those plugins apply some async techniques in their code.

To resolve this, my current workaround is: Say you have an `FileType` autocmd on filetype `custom` and the purpose of this autocmd is to do some initializations for plugin `A`, then you should instead do those initializations in `A`'s keymap. Since we always call a keymap far later than the `vim.bo.filetype`/`vim.bo.buftype` being set, you're promised to always get the correct value.

**Comment by rcarriga** [comment] 2023-01-29 10:34
>  For any type I open, I get filetype unkown which cascades into missing syntax highlighting, missing lsp attach etc etc..

Are you getting a stack trace when seeing that? If so please paste it here, if not how is it appearing? This is most likely an autocmd you have setup to run on startup which doesn't work with the buffers created by nvim-dap-ui

> And my conclusion is: This problem seems to be related to those async techniques(you can find it by following the link from OP here) in their code.

If you're seeing issues please open a bug report but I'd be surprised if any of the async code has any effect on your personal config :smile: I'd say it's more likely that the issue is coming from buffers being created on setup rather than when first opened like they were previously

**Comment by abigagli** [comment] 2023-01-29 10:47
> Are you getting a stack trace when seeing that? If so please paste it here, if not how is it appearing? This is most likely an autocmd you have setup to run on startup which doesn't work with the buffers created by nvim-dap-ui

Well, no I don't get any particular error/message/stack-trace.
What seems to be reproducible is the following:

1. start nvim to open a file
2. filetype is not set
3. re-open the same file from nvim without exiting
4. filetype is now set and everything (syntax highlighting, lsp etc) works.

Please see the short attached clip with a rust file as an example (but the same happens with cpp or loa or whatever filetype I'm working with...)

As I said I'm no nvim expert so that's pretty much it as far as my diagnosing capabilities go, but I'll be happy to perform any additional tests if you can guide me through.

https://user-images.githubusercontent.com/589164/215320945-3e828105-3619-4223-9207-0325f9d1bb09.mov

**Comment by rcarriga** [comment] 2023-01-29 19:58
This could be a tonne of things I'm afraid, you'll have to check your own config for the conflict. If you can reproduce with a minimal `init.lua` then I can help further

Here is a sample that can be run with `nvim --clean -u minimal.lua`
```lua
-- ignore default config and plugins
vim.opt.runtimepath:remove(vim.fn.stdpath("config"))
vim.opt.packpath:remove(vim.fn.stdpath("data") .. "/site")
vim.opt.termguicolors = true
vim.opt.laststatus = 0

-- append test directory
local test_dir = "/tmp/nvim-config"
vim.opt.runtimepath:append(vim.fn.expand(test_dir))
vim.opt.packpath:append(vim.fn.expand(test_dir))

-- install packer
local install_path = test_dir .. "/pack/packer/start/packer.nvim"
local install_plugins = false

if vim.fn.empty(vim.fn.glob(install_path)) > 0 then
  vim.cmd("!git clone https://github.com/wbthomason/packer.nvim " .. install_path)
  vim.cmd("packadd packer.nvim")
  install_plugins = true
end

local packer = require("packer")

packer.init({
  package_root = test_dir .. "/pack",
  compile_path = test_dir .. "/plugin/packer_compiled.lua",
})

packer.startup(function(use)
  -- Packer can manage itself
  use("wbthomason/packer.nvim")

  use({ "mfussenegger/nvim-dap" })

  use({
    "rcarriga/nvim-dap-ui",
    requires = "mfussenegger/nvim-dap",
    after = "nvim-dap",
    config = function()
      require("dapui").setup({})
    end,
  })

  if install_plugins then
    packer.sync()
  end
end)

vim.cmd([[
command! DapUIToggle lua require("dapui").toggle()
]])
```

**Comment by jdrouhard** [comment] 2023-02-02 02:20
<details>
<summary>Here's a repro</summary>

```lua
local root = vim.fn.fnamemodify("./.repro", ":p")

for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  --"folke/tokyonight.nvim",
  {
    "mfussenegger/nvim-dap",
    dependencies = { "rcarriga/nvim-dap-ui" },
    event = "BufReadPost",
    config = function()
      require("dapui").setup()
    end,
  }
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("habamax")
```
</details>

It seems to only occur if dap and dapui are loaded lazily with `BufReadPost`. Seems like there is a race condition with this autocmd where filetype detection ends up not running if dapui is loaded and set up on it as well.

**Comment by abigagli** [comment] 2023-02-02 09:55
Oh, many thanks for investigating this.
I can confirm it is indeed something race-y, since sometimes the problem just disappears by itself and I keep working for hours before it reappears again.
As I'm using Astronvim, which handles dap and dap-ui, I'll refer to this discussion and see if they can apply the suggested workaround to their configuration.

**Comment by rcarriga** [comment] 2023-02-07 09:26
Closing this as the issue is with core and there is a workaround

**Closed by rcarriga** 2023-02-07 09:26 UTC

**Comment by jdrouhard** [comment] 2023-02-07 16:40
Is there an upstream bug we can follow?
