### ISSUE TITLE
Control panel for stepping

### ISSUE THREAD

**Issue by vanhtuan0409** [rcarriga/nvim-dap-ui#65] opened 2021-11-12 02:53 UTC
Hi, is it possible that we can add a sidebar's element for step over/step out/step in/ ... etc?

Currently, all those actions are mapped to F keys but it would be nicer to have a UI for that

**Comment by rcarriga** [comment] 2022-01-11 08:51
I've had an initial go at this but couldn't get a version that worked well with clicking unfortunately. NeoVim doesn't have the `WinBar` feature that Vimspector uses which is why it also doesn't have a control panel for NeoVim. If somebody can create a nice, clickable window, I'd be happy to adapt it into nvim-dap-ui

**Comment by vanhtuan0409** [comment] 2022-01-12 02:28
hmmm, is a panel with only keybinding to `<CR>` easier for you? I dont think we need UI clicking

**Comment by ayoubelmhamdi** [comment] 2022-06-24 10:47
> I've had an initial go at this but couldn't get a version that worked well with clicking unfortunately. NeoVim doesn't have the `WinBar` feature that Vimspector uses which is why it also doesn't have a control panel for NeoVim. If somebody can create a nice, clickable window, I'd be happy to adapt it into nvim-dap-ui

neovim now have `winbar`

**Comment by serhez** [comment] 2022-07-27 13:21
I second this! A UI clickable panel would be great for when you have to repeatedly step over/into lines. I have it mapped to `<leader>ds[o/i]` but typing those four symbols seems pretty annoying if you have to it many times.

**Comment by rcarriga** [comment] 2022-08-27 13:30
I've got this implemented  in #128 if people want to try it out. It requires the winbar feature. A control panel will by default be shown in the REPL window

I'll leave it in the branch for a bit to test out, feel free to leave feedback if you have issues

**Comment by adelarsq** [comment] 2022-09-02 03:45
@rcarriga Nice. I tried to use the branch but got some errors with Neovim nightly:

![image](https://user-images.githubusercontent.com/430272/188054982-eb5357e2-95c3-4b57-b016-9281c3c9e2bc.png)

**Comment by rcarriga** [comment] 2022-09-10 14:40
Thanks for reporting! Can you try with latest commit?

**Comment by adelarsq** [comment] 2022-09-11 02:26
@rcarriga I did a little test and debugging didn't show the errors but also didn't show the winbar. Maybe some conflict?
I will try tomorrow or monday a better test.

**Comment by rcarriga** [comment] 2022-09-11 10:43
Strange, do you have the REPL in a window? Can you provide your config?

In case you're confident enough to dig around, this line https://github.com/rcarriga/nvim-dap-ui/blob/feat/control-panel/lua/dapui/init.lua#L174 is returning `-1` which means that the buffer has no window which is odd because it's triggered by a `BufWinEnter` event so it should have a window.

**Comment by adelarsq** [comment] 2022-09-11 15:45
@rcarriga I will take a look. Yesterday I took a look at the sources and everything was ok, but it didn't work. I'll try to find out what the problem is.

**Comment by rcarriga** [comment] 2022-09-20 07:44
Closing as this is now in master

**Closed by rcarriga** 2022-09-20 07:44 UTC
Labels: enhancement

**Comment by adelarsq** [comment] 2022-10-07 22:49
@rcarriga I got some time to test why this feature isn't working for me.

On this line `buf_name` is `\[dap-repl\]` instead of `[dap-repl]`:
https://github.com/rcarriga/nvim-dap-ui/blob/1cd4764221c91686dcf4d6b62d7a7b2d112e0b13/lua/dapui/init.lua#L188

So the function returns `-1` instead of the window id.

For testing pourposes changing the line to `win = vim.fn.bufwinid('[dap-repl]')` works as expected:

![image](https://user-images.githubusercontent.com/430272/194672484-b1f4e45c-5ffd-44dc-90b4-40ac2562f18d.png)
