### ISSUE TITLE
(feature) Parallel stacks view

### ISSUE THREAD

**Issue by amar-laksh** [rcarriga/nvim-dap-ui#213] opened 2023-01-23 01:27 UTC
Love the plugin! 

It would be incredibly cool if `nvim-dap-ui` could add a `parlallel stacks view`  which shows the different threads with their frames and the directions connected by arrows. 
For example, Visual studio contains the view with the same name ( [Visual studio README)](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/debugger/using-the-parallel-stacks-window.md) :

![image](https://user-images.githubusercontent.com/12481356/213951922-a0732ea2-3047-4749-ad22-949505877e9e.png)

I am currently researching as to how to approach creating it (maybe [nui.nvim?](https://github.com/MunifTanjim/nui.nvim)) but I would love to open this as an issue so people in the community can contribute.

**Comment by rcarriga** [comment] 2023-01-25 09:25
Interesting idea. Of course we're quite limited in our rendering ability but I'm sure there's an alternate view which could achieve the same idea of showing the thread structure.

The problem is I'm not sure if we can get enough information to render such a view. The threads only have an ID and name https://microsoft.github.io/debug-adapter-protocol/specification#Types_Thread and I can't see anywhere else to get the info

**Comment by rcarriga** [comment] 2023-02-18 11:12
Closing this, as far as I can see there is no way to implement this with the DAP specification

**Closed by rcarriga** 2023-02-18 11:12 UTC
