### ISSUE TITLE
Periodic "No configuration found for `dap-repl`" error

### ISSUE THREAD

**Issue by shmerl** [rcarriga/nvim-dap-ui#319] opened 2024-01-11 23:27 UTC
I got some weird behavior from nvim-dap-ui.

Sometimes it loads OK and I can press "Continue" and it all works expected. But sometimes I get such error:

```
No configuration found for `dap-repl`. You need to add configs to `dap.configurations.dap-repl` (See `:h dap-configuration`)
```

It's really weird and I'm not sure what is causing it. What's strange is that it seems inconsistent and random.

Toggling the ui back and forth can help it.

May be there is some async loading of plugins that happens and somehow bringing up the UI too soon hits a condition when dap configs aren't loaded yet?

**Comment by rcarriga** [comment] 2024-01-13 11:08
It looks like something is calling `dap.run` while the repl is the active window. This is almost certainly an issue with your configuration so I'd recommend trying to reproduce with a minimal config to rule things out. I am closing this unless there is something to suggest that nvim-dap-ui is the issue

**Closed by rcarriga** 2024-01-13 11:08 UTC

**Comment by shmerl** [comment] 2024-01-14 01:41
I think I figured what was going on. That happens if I focus on dap-repl UI element first and press "Continue" symbol there. I suppose in that scope something goes wrong. If the focus is on the source element, then it works fine.
