### ISSUE TITLE
Error executing vim.schedule lua callback: vim/shared.lua:423: s: expected string, got nil

### ISSUE THREAD

**Issue by yingzhu146** [rcarriga/nvim-dap-ui#18] opened 2021-06-04 14:49 UTC
Then rerunning a debugging run (`dap.stop()`, then restart), I always encounter an error. Re-opening nvim everytime is a bit laborious.

```shell
Error executing vim.schedule lua callback: vim/shared.lua:423: s: expected string, got nil
stack traceback:
        vim/shared.lua:423: in function 'trim'
        ...m/plugged/nvim-dap-ui/lua/dapui/elements/breakpoints.lua:30: in function 'render_breakpoints'
        ...m/plugged/nvim-dap-ui/lua/dapui/elements/breakpoints.lua:78: in function 'render'
        ...m/plugged/nvim-dap-ui/lua/dapui/elements/breakpoints.lua:100: in function 'refresh_breakpoints'
        ...m/plugged/nvim-dap-ui/lua/dapui/elements/breakpoints.lua:127: in function 'on_open'
        .../yingzhu/.vim/plugged/nvim-dap-ui/lua/dapui/windows.lua:33: in function 'open_wins'
        .../yingzhu/.vim/plugged/nvim-dap-ui/lua/dapui/windows.lua:61: in function 'open_sidebar'
        /Users/yingzhu/.vim/plugged/nvim-dap-ui/lua/dapui.lua:156: in function 'open'
        /Users/yingzhu/.vim/plugged/nvim-dap-ui/lua/dapui.lua:127: in function 'c'
        /Users/yingzhu/.vim/plugged/nvim-dap/lua/dap/session.lua:539: in function </Users/yingzhu/.vim/plugged/nvim-dap/lua/dap/session.lua:527>
```

**Comment by rcarriga** [comment] 2021-06-04 16:14
Can you provide more info for reproduction. I can't replicate. Calling `require("dap").stop()` successfully stops the session for me without any errors. The windows stay open since the adapter is still connected, to disconnect altogether `require("dap").disconnect()` should be used (see #13).

**Comment by yingzhu146** [comment] 2021-06-06 01:53
sorry for the slow reply - right now can't reproduce myself again after restart. I'll report back once I get into the situation again. thanks for your help and have an awesome weekend!

**Comment by HiPhish** [comment] 2021-06-13 19:26
I just want to chime in that have the same issue when calling `dap.run()`, but I cannot reproduce it reliably. It happens sometimes, but I cannot predict when.

**Comment by naefl** [comment] 2021-06-18 19:47
Same issue. it appears to happen when I've stopped at a breakpoint and then try to add another breakpoint somewhere. after that, every possible operation will trigger this error (from triggering up/down callstack, continue, ...)

**Comment by rcarriga** [comment] 2021-06-19 09:51
OK since this is happening to multiple people I've put in a workaround. I haven't been able to reproduce myself so can't verify that everything is working now. 

Please report back if something still doesn't work!

**Comment by y1rn** [comment] 2021-07-09 10:08
same issue

**Comment by rcarriga** [comment] 2021-09-30 07:47
This thread has been quiet for a while and I'm wondering if there is anyone
still experiencing it. If so, please let me know! Otherwise, I will be closing
this issue as there has been no reliable report since the last fix put in.

**Comment by HiPhish** [comment] 2021-10-02 12:30
So far everything has been working fine for me for the last several weeks.

**Closed** 2021-10-04 07:34 UTC
Labels: awaiting response
