### ISSUE TITLE
[Feature Request]: Make the repl window automatically scroll to the last line

### ISSUE THREAD

**Issue by mweisshaupt1988** [rcarriga/nvim-dap-ui#126] opened 2022-08-08 13:18 UTC
To be honest I don't know if this is possible in nvim but it would be nice if the repl window would auto scroll to the last line similar to how IDEs do it with the output window.

This pseudo code for example would produce a lot of manual scrolling to follow the progress and would benefit from an autoscroll feature:
`for (i=0; i<1000;i++) {
  println("Currentnumber: $i")
}`

**Comment by rcarriga** [comment] 2022-08-10 07:19
This should probably be a feature request on nvim-dap, as it controls the REPL buffer.

**Comment by mweisshaupt1988** [comment] 2022-08-10 09:13
Ok, I was not sure about this if it is a ui feature or not. I'll open a feature request there too. Thank you.

**Comment by rcarriga** [comment] 2022-08-27 15:44
Closing as the issue is being tracked in nvim-dap

**Closed by rcarriga** 2022-08-27 15:44 UTC

**Comment by Mr-LLLLL** [comment] 2023-03-20 06:45
this issue is resolved?

**Comment by Jendker** [comment] 2023-11-08 13:27
I have the same question. The DAP Console doesn't autoscroll to the latest output for me.
