### ISSUE TITLE
Unexpected insert behaviour after updating 

### ISSUE THREAD

**Issue by Bryaneven** [rcarriga/nvim-dap-ui#227] opened 2023-02-01 16:47 UTC
I updated the plugin from 2.6.0 to 3.2.5  this morning , after using the REPL and closing it , i now have a strange behaviour where every keys i press put me in insert mode and a new line pop under my lualine.

<img width="2495" alt="Screenshot 2023-02-01 at 14 53 24" src="https://user-images.githubusercontent.com/59363064/216106481-0c387152-63cc-4e32-9de6-6399a4ea1f17.png">

Downgrading the version to 3.2.2 did the trick so it seems that the issue is caused by the v3.2.3 changes .

**Comment by LucasTavaresA** [comment] 2023-02-06 01:28
im having that, happens at 3953824

**Comment by huyiqun** [comment] 2023-02-07 00:40
experiencing the same problem

**Comment by willydeliege** [comment] 2023-02-07 21:20
Same here

**Comment by rcarriga** [comment] 2023-02-09 13:06
If someone can provide a minimal init.lua to reproduce, I can figure out the issue as right now unfortunately I cannot reproduce. 
Here's a starter one you can run with `nvim --clean -u minimal.lua`
```lua
-- ignore default config and plugins
vim.opt.runtimepath:remove(vim.fn.stdpath("config"))
vim.opt.packpath:remove(vim.fn.stdpath("data") .. "/site")
vim.opt.termguicolors = true
vim.opt.laststatus = 0

-- append test directory
local test_dir = "/tmp/nvim-config"
vim.opt.runtimepath:append(vim.fn.expand(test_dir))
vim.opt.packpath:append(vim.fn.expand(test_dir))

-- install packer
local install_path = test_dir .. "/pack/packer/start/packer.nvim"
local install_plugins = false

if vim.fn.empty(vim.fn.glob(install_path)) > 0 then
  vim.cmd("!git clone https://github.com/wbthomason/packer.nvim " .. install_path)
  vim.cmd("packadd packer.nvim")
  install_plugins = true
end

local packer = require("packer")

packer.init({
  package_root = test_dir .. "/pack",
  compile_path = test_dir .. "/plugin/packer_compiled.lua",
})

packer.startup(function(use)
  -- Packer can manage itself
  use("wbthomason/packer.nvim")

  use({ "mfussenegger/nvim-dap" })

  use({
    "rcarriga/nvim-dap-ui",
    requires = "mfussenegger/nvim-dap",
    config = function()
      require("dapui").setup({})
    end,
  })

  if install_plugins then
    packer.sync()
  end
end)

vim.cmd([[
command! DapUIToggle lua require("dapui").toggle()
]])
```

**Comment by yao-weijie** [comment] 2023-03-29 14:20
In `dapui` old versions, `repl` will not be closed automatically, so I need to add `dap.repl.close()`, 

But in `dapui` recent versions, `repl` closed behaviour is controlled by `dapui.close()`, that't the difference :)

**Comment by marcomayer** [comment] 2023-04-05 08:46
I'm also having issues with insert mode after calling dapui.close(). The only thing that fixes it is calling dapui.open() again, then I can type normally but whenever I call close again it's screwed :/

Unfortunately don't have the time to dive deeper right now but in my case the dap.repl.close() workaround doesn't do it.

**Comment by bcp-dev-ops** [comment] 2023-04-14 17:22
same problem as well

**Comment by bcp-dev-ops** [comment] 2023-04-14 17:38
#262 can confirm that updating to nightly neovim resolves this for me

**Comment by rcarriga** [comment] 2023-05-29 20:54
Closing as the fix is in neovim, not nvim-dap-ui

**Closed by rcarriga** 2023-05-29 20:54 UTC
