### ISSUE TITLE
Floating window doesn't appear to work as expected

### ISSUE THREAD

**Issue by RonanMacF** [rcarriga/nvim-dap-ui#21] opened 2021-06-10 14:23 UTC
The README states that to activate the floating window you call `require("dapui").float_element(<element ID>)`. In the README an example element ID is `stacks`. So I execute `require("dapui").float_element(stacks)`. This then prompts me for an element ID again, however, it seems to only take numbers, I tried using numbers 1-10 but nothing happened. My expectation is that by executing `require("dapui").float_element(stacks)` an additional prompt would not appear and instead just the floating window would.

**Comment by rcarriga** [comment] 2021-06-10 16:51
Assuming you're reproducing your code reliably the issue is that you are passing `stacks` rather than `"stacks"`. Lua reads the former as a variable, which rather than throwing an error because it doesn't exist, it assigns to `nil`. I'll adjust the README to make it more obvious to pass a string

**Comment by RonanMacF** [comment] 2021-06-10 16:58
my bad your spot on, quoting it made the floating window pop up.

I see the floating window appears to be printed at the top left corner, from the screenshot it appeared to appear at the cursor (which would be desired). I don't see any configuration option for this in the README, is there one?

**Comment by rcarriga** [comment] 2021-06-10 19:39
Hmm no it should be by your cursor, could you provide an example file and position where it doesn't?

**Comment by RonanMacF** [comment] 2021-06-11 10:48
interestingly I have discovered this only happens when I call the func directly e.g. `:lua require("dapui").float_element("scopes")`. Using a mapping e.g. `nnoremap <silent> <M-s> :lua require'dapui'.float_element("scopes")<cr>` makes it appear at the cursor. I have no idea how this could happen

**Comment by rcarriga** [comment] 2021-06-11 12:25
Aha that actually makes sense, it's because of how it is getting the cursor position. I'll have to play around to get a fix for this

**Comment by rcarriga** [comment] 2021-06-12 16:49
Found a delightful little hack to get around this. All fixed

**Closed** 2021-06-12 16:48 UTC
Labels: bug

**Comment by Mte90** [comment] 2024-01-16 18:01
I have the same issues:

```
vim.keymap.set('n', '<F2>', ":lua require'dapui'.float_element('scopes', {position = 'center'})<CR>")
```

No popup is opened also with "repl" only with console it is showed the popup but sometimes is empty.
